version: '2.4'
services:
  sonarqube:
    build:
      context: ./docker/sonarqube
      dockerfile: Dockerfile
    image: sonarqube:5.2
    container_name: sonarqube
    ports:
      - "9000:9000"
    volumes:
      - ./docker/data/sonarqube/data:/opt/sonarqube/data
      - ./docker/data/sonarqube/logs:/opt/sonarqube/logs
