version: '2.4'
services:
  prometheus_grok_exporter:
    build:
      context: ./docker/prometheus/grok_exporter
      dockerfile: Dockerfile
    image: prometheus_grok_exporter:1.0.0.RC5
    container_name: grok_exporter
    ports:
      - "10197:10197"
    volumes:
#      - ./docker/data/prometheus:/opt/prometheus
      - ./docker/prometheus/grok_exporter/config_v3.yml:/opt/prometheus/grok_exporter/config.yml
#      - ./docker/prometheus/grok_exporter/F2E_ActivityStatusLog_pattern:/opt/prometheus/grok_exporter/patterns/ing_f2e
      - ./docker/prometheus/grok_exporter/sample_logs:/opt/prometheus/grok_exporter/sample_logs
